### ISSUE TITLE
No get String  

### ISSUE THREAD

**Issue by Ahmed49** [mejdi14/Flat-Dialog-Android#3]
.setTitle(R.string.error_title)
				.setSubtitle(R.string.error_O)
R.String .Delete
error: void cannot be dereferenced

**Comment by mejdi14** [comment]
the problem here is not clear, can you provide a full sample of your code

**Comment by Ahmedomarpro** [comment]
FlatDialog flatDialog = new FlatDialog(activity);
		flatDialog
				.setIcon(R.drawable.crying)
				/*.setTitle(" Error")
				.setSubtitle("Error Top")
				.setFirstButtonText(" WiFi")
				.setSecondButtonText("OK ")*/
				
not use code in Error in retrievein Int .setTitle(R.string.Ms_cANCEL)
 retrievein  in String Not Work in R.String.Ms_cANCEL


		//.isCancelable(true)

		this Code Error--> . withFirstButtonListner(new View.OnClickListener() {
					@Override
					public void onClick(View view) {
						Toast.makeText(activity, R.string.toast_Intrnet, Toast.LENGTH_SHORT).show();
						activity.startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));

						flatDialog.dismiss();
					}
				})
				.withSecondButtonListner(new View.OnClickListener() {
					@Override
					public void onClick(View v) {
						flatDialog.dismiss();
						activity.finish();
					}
				})

				.isCancelable(true)
				.show();

	}

**Comment by mejdi14** [comment]
thank you for reporting the issue, it will be fixed as soon as possible in a new release

**Comment by Ahmed49** [comment]
Thanks for your understanding of the problem @mejdi14
