### ISSUE TITLE
Any possibility on lowering min SDK?

### ISSUE THREAD

**Issue by diegopefm** [mejdi14/Flat-Dialog-Android#5]
I don't know if this is the correct place where I can ask this because my question is not about an issue, so sorry if not, but don't know where to ask.

I just love this cool dialog library and started using it in my Android project as soon as I've come across with it, but I have a little problem. I have an old Asus SDK 18 tablet I use for testing my app in a tablet but Flat-Dialog min SDK is 19 so as soon as I've included it in my project my app stopped running in my Asus Android 4.3 SDK 18 tablet.

I've downloaded the source, edited gradle and set min SDK to 18 and noticed library still compiles with no errors, so my question is if could it be possible to lower min SDK as much as possible (or at least take it to 18) so I can run it on my tablet.

Best, and congrats for such a great work and beautiful library.

**Comment by mejdi14** [comment]
hi diegopefm
thank you for pointing out this problem, i changed the min sdk to 15 and it works just fine,
you can use the new version (1.0.5)
have a nice day
