### ISSUE TITLE
Can't change EditText's input type

### ISSUE THREAD

**Issue by MiguelAlvesMiguel** [mejdi14/Flat-Dialog-Android#6]
.setFirstTextFieldInputType(InputType.TYPE_TEXT_VARIATION_PASSWORD) is not working at least, no change at all.

**Comment by MiguelAlvesMiguel** [comment]
For anyone with this problem, changing the TransformationMethod works, but you need to fork the repository,

**Comment by mejdi14** [comment]
sorry for the issue, i will take a look at it as soon as possible

**Comment by ezechuka** [comment]
I made a PR for this, please review it @mejdi14.
Thanks

**Comment by mejdi14** [comment]
@ezechuka thank you so much for the contribution
