### ISSUE TITLE
Dialog cut on small screens.

### ISSUE THREAD

**Issue by cico1980** [mejdi14/Flat-Dialog-Android#8]
When executed on small screens, for example on a 400x800: hdpi emulator, the right side of the dialog, including text and bottons, are cut off.

**Comment by mejdi14** [comment]
sorry for that, i will try to find some time to fix this one :(

**Comment by Amark18** [comment]
Hey @mejdi14, thanks for making Flat Dialog. I was wondering if you were able to fix this. It would be nice if whatever inside the dialog is scrollable in the case it is cut off.

**Comment by mejdi14** [comment]
Hey @Amark18 , i just added it to my todo list for this weekend, i have completely forgot about this one

**Comment by Amark18** [comment]
Thanks @mejdi14, I appreciate it

**Comment by ezechuka** [comment]
@mejdi14, I created a PR for this, please review it.
Thanks
